### PR TITLE
Update to nix 0.24.1.

### LINKED ISSUE #24: nix 0.24 made VsockAddr opaque
https://github.com/nix-rust/nix/pull/1614

vsock won't build with nix >= 0.24.

<details>
<summary>Build log</summary>

```
error[E0423]: cannot initialize a tuple struct which contains private fields
    --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:117:32
     |
117  |             Ok(SockAddr::Vsock(VsockAddr(vsock_addr)))
     |                                ^^^^^^^^^ help: a local variable with a similar name exists: `vsock_addr`
     |
note: constructor is not visible here due to private fields
    --> /tmp/tmp.xk1r9Xh1Kg/registry/nix-0.24.1/src/sys/socket/addr.rs:2518:26
     |
2518 |     pub struct VsockAddr(pub(in super::super) sockaddr_vm);
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private field

error[E0423]: cannot initialize a tuple struct which contains private fields
    --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:281:32
     |
281  |             Ok(SockAddr::Vsock(VsockAddr(vsock_addr)))
     |                                ^^^^^^^^^ help: a local variable with a similar name exists: `vsock_addr`
     |
note: constructor is not visible here due to private fields
    --> /tmp/tmp.xk1r9Xh1Kg/registry/nix-0.24.1/src/sys/socket/addr.rs:2518:26
     |
2518 |     pub struct VsockAddr(pub(in super::super) sockaddr_vm);
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private field

error[E0423]: cannot initialize a tuple struct which contains private fields
    --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:305:32
     |
305  |             Ok(SockAddr::Vsock(VsockAddr(vsock_addr)))
     |                                ^^^^^^^^^ help: a local variable with a similar name exists: `vsock_addr`
     |
note: constructor is not visible here due to private fields
    --> /tmp/tmp.xk1r9Xh1Kg/registry/nix-0.24.1/src/sys/socket/addr.rs:2518:26
     |
2518 |     pub struct VsockAddr(pub(in super::super) sockaddr_vm);
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private field

warning: use of deprecated enum `nix::sys::socket::SockAddr`: use SockaddrLike or SockaddrStorage instead
  --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:29:28
   |
29 | pub use nix::sys::socket::{SockAddr, VsockAddr};
   |                            ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated enum `nix::sys::socket::SockAddr`: use SockaddrLike or SockaddrStorage instead
  --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:57:24
   |
57 |     pub fn bind(addr: &SockAddr) -> Result<VsockListener> {
   |                        ^^^^^^^^

warning: use of deprecated variant `nix::sys::socket::SockAddr::Vsock`: use SockaddrLike or SockaddrStorage instead
  --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:58:47
   |
58 |         let mut vsock_addr = if let SockAddr::Vsock(addr) = addr {
   |                                               ^^^^^

warning: use of deprecated variant `nix::sys::socket::SockAddr::Vsock`: use SockaddrLike or SockaddrStorage instead
  --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:94:31
   |
94 |         Self::bind(&SockAddr::Vsock(VsockAddr::new(cid, port)))
   |                               ^^^^^

warning: use of deprecated enum `nix::sys::socket::SockAddr`: use SockaddrLike or SockaddrStorage instead
  --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:98:40
   |
98 |     pub fn local_addr(&self) -> Result<SockAddr> {
   |                                        ^^^^^^^^

warning: use of deprecated variant `nix::sys::socket::SockAddr::Vsock`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:117:26
    |
117 |             Ok(SockAddr::Vsock(VsockAddr(vsock_addr)))
    |                          ^^^^^

warning: use of deprecated enum `nix::sys::socket::SockAddr`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:127:50
    |
127 |     pub fn accept(&self) -> Result<(VsockStream, SockAddr)> {
    |                                                  ^^^^^^^^

warning: use of deprecated variant `nix::sys::socket::SockAddr::Vsock`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:149:27
    |
149 |                 SockAddr::Vsock(VsockAddr::new(vsock_addr.svm_cid, vsock_addr.svm_port)),
    |                           ^^^^^

warning: use of deprecated enum `nix::sys::socket::SockAddr`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:228:27
    |
228 |     pub fn connect(addr: &SockAddr) -> Result<Self> {
    |                           ^^^^^^^^

warning: use of deprecated variant `nix::sys::socket::SockAddr::Vsock`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:229:43
    |
229 |         let vsock_addr = if let SockAddr::Vsock(addr) = addr {
    |                                           ^^^^^

warning: use of deprecated variant `nix::sys::socket::SockAddr::Vsock`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:258:34
    |
258 |         Self::connect(&SockAddr::Vsock(VsockAddr::new(cid, port)))
    |                                  ^^^^^

warning: use of deprecated enum `nix::sys::socket::SockAddr`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:262:39
    |
262 |     pub fn peer_addr(&self) -> Result<SockAddr> {
    |                                       ^^^^^^^^

warning: use of deprecated variant `nix::sys::socket::SockAddr::Vsock`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:281:26
    |
281 |             Ok(SockAddr::Vsock(VsockAddr(vsock_addr)))
    |                          ^^^^^

warning: use of deprecated enum `nix::sys::socket::SockAddr`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:286:40
    |
286 |     pub fn local_addr(&self) -> Result<SockAddr> {
    |                                        ^^^^^^^^

warning: use of deprecated variant `nix::sys::socket::SockAddr::Vsock`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:305:26
    |
305 |             Ok(SockAddr::Vsock(VsockAddr(vsock_addr)))
    |                          ^^^^^

warning: use of deprecated field `nix::sys::socket::SockAddr::Vsock::0`: use SockaddrLike or SockaddrStorage instead
  --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:58:53
   |
58 |         let mut vsock_addr = if let SockAddr::Vsock(addr) = addr {
   |                                                     ^^^^

error[E0616]: field `0` of struct `VsockAddr` is private
  --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:59:18
   |
59 |             addr.0
   |                  ^ private field

warning: use of deprecated field `nix::sys::socket::SockAddr::Vsock::0`: use SockaddrLike or SockaddrStorage instead
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:229:49
    |
229 |         let vsock_addr = if let SockAddr::Vsock(addr) = addr {
    |                                                 ^^^^

error[E0616]: field `0` of struct `VsockAddr` is private
   --> /tmp/tmp.xk1r9Xh1Kg/registry/vsock-0.2.4/src/lib.rs:230:18
    |
230 |             addr.0
    |                  ^ private field
```

</details>

### PR DESCRIPTION
**Pull request by qwandor**
This makes the contents of `VsockAddr` private, so we have to use the provided methods instead. This is an API-breaking change.

Fixes #24.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -227,28 +219,19 @@ pub struct VsockStream {
 
 impl VsockStream {
     /// Open a connection to a remote host.
-    pub fn connect(addr: &SockAddr) -> Result<Self> {
-        let vsock_addr = if let SockAddr::Vsock(addr) = addr {
-            addr.0
-        } else {
+    pub fn connect(addr: &VsockAddr) -> Result<Self> {
+        if addr.family() != Some(AddressFamily::Vsock) {
```
Comment (Tim-Zhang) [inline src/lib.rs:223]: I think we don't need this line any more, because the family of VsockAddr must be AddressFamily::Vsock

File: src/lib.rs [hunk 2]
```diff
@@ -227,28 +219,19 @@ pub struct VsockStream {
 
 impl VsockStream {
     /// Open a connection to a remote host.
-    pub fn connect(addr: &SockAddr) -> Result<Self> {
-        let vsock_addr = if let SockAddr::Vsock(addr) = addr {
-            addr.0
-        } else {
+    pub fn connect(addr: &VsockAddr) -> Result<Self> {
```
[the remark this answers is not in the document]
Comment (qwandor) [reply src/lib.rs]: Done.

File: src/lib.rs (hunk 1 above)
Comment (qwandor) [reply src/lib.rs:223]: It is necessary now that I have changed the type to `impl SockaddrLike` as requested above.

**Review by Tim-Zhang — APPROVED** [review]
LGTM thanks @qwandor

**Comment by Tim-Zhang** [comment]
It need a major version release later, I think we can do it after the remaining draft pull requests merged.
